### ISSUE TITLE
Update syntax of RES_LOC for mcdoc

### ISSUE THREAD

**Issue by SPGoding** [SpyglassMC/Spyglass#1026]
Currently `RES_LOC` mandates there being a colon (`:`) to disambiguate them between identifiers, however a slash (`/`) could also be used to disambiguate them, so we could make the syntax requirement for resource locations less strict by mandating the existense of either a colon (`:`) or a slash (`/`).

```[tasklist]
### Tasks
- [ ] Update documentation for `RES_LOC` at `docs/user/mcdoc/index.adoc`.
- [ ] Update `resLoc` parser at `packages/mcdoc/src/parser/index.ts`
- [ ] Add `bar/baz` as a test case for `resLoc` at `packages/mcdoc/test/parser/index.spec.ts`
```

**Comment by misode** [comment]
Are you sure there are no cases where resource lcoations are used without a string as second option? That would mean a breaking change. Is there no parser construct where it will result in the first that matches?

**Comment by SPGoding** [comment]
A string has to be quoted, and an identifier cannot have `:` or `/` in it, so i don't see any potential conflicts this can introduce. Or did you mean something else?

**Comment by misode** [comment]
@SPGoding Is this issue still relevant? Is it a requirement for v4.0?

**Comment by SPGoding** [comment]
It's still relevant but not a requirement for v4. I'll rewrite the issue body to make it clearer what this issue is about.

**Comment by SPGoding** [comment]
Actually upon second thoughts this just make the resource location parser more complicated for a tiny benefit of being able to write resource locations like `minecraft:foo/bar` without the namespace part. Afaik there aren't much resource locations under the `minecraft` namespace that have multiple parts in the path segment. So I'm gonna close this as not planned.
