### ISSUE TITLE
Finalize & officially support custom resource declaration in the config

### ISSUE THREAD

**Issue by MulverineX** [SpyglassMC/Spyglass#1254]
```[tasklist]
### Tasks
- [x] Create initial implementation, https://github.com/SpyglassMC/Spyglass/pull/1231
- [ ] Handle problems with spec & implementation
- [ ] Remove experimental status, release in a minor update
```
